Initial Environment Setup Trello Card Completed
learn-academy-2022-charlie/apartment-app-jennerdulce pull request #1
Opened 2022-07-06 23:02 UTC by jennerdulce

2022-07-06 23:09 UTC, SunkissedQueen requested changes
Please update your Trello to reflect all the changes that have occurred. Right now based on the Trello, the only change that would have taken place is the db/seeds. Ping me when that is updated.

2022-07-06 23:55 UTC, jennerdulce reviewed
Moved Unprotected Index Trello Card to Doing

2022-07-07 00:11 UTC, jennerdulce reviewed
All changes are correct

2022-07-07 00:23 UTC, SunkissedQueen approved these changes

2022-07-07 01:47 UTC, merged